name: CICD

on:
  push:
    branches: [ branch_carpetas ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

jobs:
  ci:
    permissions: write-all
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Commit
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

  cd:
    needs: [ci]
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          pip install -r .github/workflows/requirements.txt
          python -B src/pipelines/pipeline.py 
  
      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          project_id: "intento-c-enlanube"
          workload_identity_provider: "https://iam.googleapis.com/projects/567848119296/locations/global/workloadIdentityPools/aprendegithubintento/providers/githubactionsmlops"
          service_account: "mlops-service-account@intento-c-enlanube.iam.gserviceaccount.com"

      - name: Register
        run: |
          curl -X POST \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -F tags=latest \
            -F content=@pipeline.yaml \
            https://us-central1-kfp.pkg.dev/intento-c-enlanube/mlops/
